[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.0.0-rc.1" }
rotrieve = { source = "roblox/rotriever", version = "0.5.0-alpha.3" }
selene = { source = "Kampfkarren/selene", version = "0.13.0" }
