[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.2.1" }
rotrieve = { source = "roblox/rotriever", version = "=0.5.5" }
selene = { source = "Kampfkarren/selene", version = "=0.22.0" }
stylua = { source = "johnnymorganz/stylua", version = "=0.15.1" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "5.x.x" }
