[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.2.0" }
rotrieve = { source = "roblox/rotriever", version = "=0.5.5" }
selene = { source = "Kampfkarren/selene", version = "=0.21.1" }
stylua = { source = "johnnymorganz/stylua", version = "=0.15.1" }
