[package]
name = "RoactNavigation"
version = "0.4.1"
author = "Roblox"
content_root = "src"

[dependencies]
Roact = "github.com/roblox/roact@1.2"
Cryo = "github.com/roblox/cryo@1.0"
Otter = "github.com/roblox/otter@0.1"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.1.5"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@1.1.1"
Rhodium = "github.com/roblox/rhodium@0.2.4"
RoactCompat = { git = "https://github.com/roblox/roact-alignment" }
