[package]
name = "roblox/roact-navigation"
version = "0.2.4"
author = "Roblox"
content_root = "src"

[dependencies]
Roact = "roblox/roact@1.2"
Cryo = "roblox/cryo@1.0"
Otter = "roblox/otter@0.1"
StateTable = "roblox/state-table@0.1"
