[package]
name = "RoactNavigation"
version = "0.5.0"
authors = ["Roblox"]
content_root = "src"
files = ["*", "!**/_tests_/**"]

[dependencies]
Roact = "github.com/roblox/roact@1.2"
Cryo = "github.com/roblox/cryo@1.0"
Otter = "github.com/roblox/otter@0.1"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.6"
RegExp = "github.com/roblox/luau-regexp@0.2.0"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.3.1"
Rhodium = "github.com/roblox/rhodium@0.2.4"
RoactCompat = "github.com/roblox/roact-alignment@17.0.1-rc.6"
