[package]
name = "roact-navigation"
version = "0.1.4"
author = "David Brooks"
content_root = "src"

[dependencies]
Roact = { git = "https://github.com/Roblox/Roact", rev = "master" }
Cryo = { git = "https://github.com/Roblox/cryo", rev = "master" }
Otter = { git = "https://github.com/Roblox/Otter", rev = "master" }

