[package]
name = "RoactNavigation"
version = "0.5.2"
authors = ["Roblox"]
content_root = "src"
files = ["*", "!**/_tests_/**", "!.robloxrc"]

[dependencies]
React = "github.com/roblox/roact-alignment@17.0.1-rc.11"
Roact = { target = "github.com/roblox/roact-alignment", version = "17.0.1-rc.11", package = "RoactCompat"}
Cryo = "github.com/roblox/cryo@1.0"
Otter = "github.com/roblox/otter@0.1"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.4.1"
RegExp = "github.com/roblox/luau-regexp@0.2.0"

[dev_dependencies]
ReactRoblox = "github.com/roblox/roact-alignment@17.0.1-rc.11"
JestGlobals = "github.com/roblox/jest-roblox@2.4.1"
Rhodium = "github.com/roblox/rhodium@0.2.4"
